{{- if .Values.backend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  labels:
    {{- include "njord-backend.labels" . | nindent 4 }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.backend.ingress.className }}
  rules:
    - host: {{ .Values.backend.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.backend.ingress.path }}
            pathType: {{ .Values.backend.ingress.pathType }}
            backend:
              service:
                name: backend
                port:
                  number: {{ .Values.backend.service.port }}
  {{- with .Values.backend.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
