/**
 * Parses src/index.css → computes WCAG contrast ratios for all text/surface token pairs
 * → writes src/tokens/colorPairings.ts (auto-generated agent lookup table).
 *
 * Run: npm run generate:pairings
 * When: after ANY change to color tokens in src/index.css
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// — WCAG 2.1 contrast math —

function hexToLinear(hex: string): [number, number, number] {
  const h = hex.replace('#', '');
  const r = parseInt(h.slice(0, 2), 16) / 255;
  const g = parseInt(h.slice(2, 4), 16) / 255;
  const b = parseInt(h.slice(4, 6), 16) / 255;
  const linearize = (c: number) =>
    c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
  return [linearize(r), linearize(g), linearize(b)];
}

function relativeLuminance(hex: string): number {
  const [r, g, b] = hexToLinear(hex);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrastRatio(hex1: string, hex2: string): number {
  const l1 = relativeLuminance(hex1);
  const l2 = relativeLuminance(hex2);
  const lighter = Math.max(l1, l2);
  const darker = Math.min(l1, l2);
  return Math.round(((lighter + 0.05) / (darker + 0.05)) * 100) / 100;
}

// — CSS token extraction —

function extractBlock(css: string, blockPattern: RegExp): string {
  const match = css.match(blockPattern);
  return match ? match[1] : '';
}

function extractTokens(block: string): Record<string, string> {
  const tokens: Record<string, string> = {};
  const tokenRe = /--(color-[\w-]+):\s*(#[0-9a-fA-F]{6})\b/g;
  let m: RegExpExecArray | null;
  while ((m = tokenRe.exec(block)) !== null) {
    tokens[m[1]] = m[2].toUpperCase();
  }
  return tokens;
}

// Token classification — matches new WCAG AAA palette in src/index.css
const SURFACE_TOKENS = [
  'color-bg-primary',
  'color-bg-card',
  'color-bg-hover',
];

const TEXT_TOKENS = [
  'color-text-primary',
  'color-text-secondary',
  'color-text-muted',
  'color-accent-primary',
  'color-accent-secondary',
  'color-success',
  'color-danger',
];

interface TokenPairing {
  /** Hex value of this surface */
  hex: string;
  /** Text tokens with contrast ≥4.5:1 — safe for normal-size readable text */
  validText: string[];
  /** Text tokens with contrast ≥3:1 but <4.5:1 — large text / UI elements only */
  validLargeText: string[];
  /** Text tokens with contrast <3:1 — NEVER use for any text or interactive element */
  forbidden: string[];
}

function computePairings(
  surfaceTokens: typeof SURFACE_TOKENS,
  textTokens: typeof TEXT_TOKENS,
  allTokens: Record<string, string>,
): Record<string, TokenPairing> {
  const result: Record<string, TokenPairing> = {};

  for (const surfaceName of surfaceTokens) {
    const surfaceHex = allTokens[surfaceName];
    if (!surfaceHex) continue;

    const pairing: TokenPairing = {
      hex: surfaceHex,
      validText: [],
      validLargeText: [],
      forbidden: [],
    };

    for (const textName of textTokens) {
      const textHex = allTokens[textName];
      if (!textHex) continue;

      const ratio = contrastRatio(surfaceHex, textHex);
      // Tailwind class name: color-on-dark → text-on-dark
      const tailwindClass = textName.replace('color-', 'text-');

      if (ratio >= 4.5) {
        pairing.validText.push(`${tailwindClass} (${ratio}:1)`);
      } else if (ratio >= 3.0) {
        pairing.validLargeText.push(`${tailwindClass} (${ratio}:1)`);
      } else {
        pairing.forbidden.push(`${tailwindClass} (${ratio}:1)`);
      }
    }

    // Tailwind class: color-surface → bg-surface
    const tailwindSurface = surfaceName.replace('color-', 'bg-');
    result[tailwindSurface] = pairing;
  }

  return result;
}

// — Main —

const cssPath = path.resolve(__dirname, '../src/index.css');
const css = fs.readFileSync(cssPath, 'utf-8');

// @theme {} = light mode token definitions
const themeBlock = extractBlock(css, /@theme\s*\{([^}]+(?:\{[^}]*\}[^}]*)*)\}/s);
const lightTokensRaw = extractTokens(themeBlock);

// html.dark {} = dark mode overrides
const darkBlock = extractBlock(css, /html\.dark\s*\{([^}]+)\}/s);
const darkOverrides = extractTokens(darkBlock);

// Merge: start with light tokens, apply dark overrides
const lightTokens = lightTokensRaw;
const darkTokens = { ...lightTokensRaw, ...darkOverrides };

const lightPairings = computePairings(SURFACE_TOKENS, TEXT_TOKENS, lightTokens);
const darkPairings = computePairings(SURFACE_TOKENS, TEXT_TOKENS, darkTokens);

const output = `// AUTO-GENERATED by scripts/generate-pairings.ts
// Re-run: npm run generate:pairings
//
// This file is the agent lookup table for safe color pairings.
// Before applying any dark: text token override, verify the pairing here.
//
// Legend:
//   validText      — contrast >=4.5:1 — safe for all text sizes
//   validLargeText — contrast >=3:1   — large text (>=18px) or UI elements only
//   forbidden      — contrast <3:1    — NEVER use for text or interactive elements

export interface TokenPairing {
  hex: string;
  validText: string[];
  validLargeText: string[];
  forbidden: string[];
}

export const lightMode: Record<string, TokenPairing> = ${JSON.stringify(lightPairings, null, 2)};

export const darkMode: Record<string, TokenPairing> = ${JSON.stringify(darkPairings, null, 2)};
`;

const outPath = path.resolve(__dirname, '../src/tokens/colorPairings.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, output);

console.log('✅ Generated ' + path.relative(process.cwd(), outPath));
console.log('');
console.log('Light mode surfaces:');
for (const [surface, pairing] of Object.entries(lightPairings)) {
  console.log(`  ${surface} (${pairing.hex}): ${pairing.validText.length} valid, ${pairing.forbidden.length} forbidden`);
}
console.log('');
console.log('Dark mode surfaces:');
for (const [surface, pairing] of Object.entries(darkPairings)) {
  console.log(`  ${surface} (${pairing.hex}): ${pairing.validText.length} valid, ${pairing.forbidden.length} forbidden`);
}
