// AUTO-GENERATED by scripts/generate-pairings.ts
// Last generated: 2026-05-01T15:39:00.252Z
// Re-run: npm run generate:pairings
//
// This file is the agent lookup table for safe color pairings.
// Before applying any dark: text token override, verify the pairing here.
//
// Legend:
//   validText      — contrast >=4.5:1 — safe for all text sizes
//   validLargeText — contrast >=3:1   — large text (>=18px) or UI elements only
//   forbidden      — contrast <3:1    — NEVER use for text or interactive elements

export interface TokenPairing {
  hex: string;
  validText: string[];
  validLargeText: string[];
  forbidden: string[];
}

export const lightMode: Record<string, TokenPairing> = {
  "bg-surface": {
    "hex": "#FFFFFF",
    "validText": [
      "text-heading (12.89:1)",
      "text-body (6.66:1)",
      "text-muted (4.7:1)"
    ],
    "validLargeText": [],
    "forbidden": [
      "text-faint (1.82:1)",
      "text-on-dark (1:1)",
      "text-on-dark-muted (1.53:1)"
    ]
  },
  "bg-surface-alt": {
    "hex": "#F8F9FA",
    "validText": [
      "text-heading (12.23:1)",
      "text-body (6.31:1)"
    ],
    "validLargeText": [
      "text-muted (4.46:1)"
    ],
    "forbidden": [
      "text-faint (1.73:1)",
      "text-on-dark (1.05:1)",
      "text-on-dark-muted (1.45:1)"
    ]
  },
  "bg-surface-muted": {
    "hex": "#F1F2F4",
    "validText": [
      "text-heading (11.5:1)",
      "text-body (5.94:1)"
    ],
    "validLargeText": [
      "text-muted (4.2:1)"
    ],
    "forbidden": [
      "text-faint (1.63:1)",
      "text-on-dark (1.12:1)",
      "text-on-dark-muted (1.37:1)"
    ]
  },
  "bg-surface-dark": {
    "hex": "#2D3142",
    "validText": [
      "text-faint (7.07:1)",
      "text-on-dark (12.89:1)",
      "text-on-dark-muted (8.43:1)"
    ],
    "validLargeText": [],
    "forbidden": [
      "text-heading (1:1)",
      "text-body (1.94:1)",
      "text-muted (2.74:1)"
    ]
  },
  "bg-surface-dark-alt": {
    "hex": "#3B4055",
    "validText": [
      "text-faint (5.62:1)",
      "text-on-dark (10.24:1)",
      "text-on-dark-muted (6.7:1)"
    ],
    "validLargeText": [],
    "forbidden": [
      "text-heading (1.26:1)",
      "text-body (1.54:1)",
      "text-muted (2.18:1)"
    ]
  }
};

export const darkMode: Record<string, TokenPairing> = {
  "bg-surface": {
    "hex": "#1E2130",
    "validText": [
      "text-heading (15.96:1)",
      "text-body (10.44:1)",
      "text-muted (5.33:1)",
      "text-on-dark (15.96:1)",
      "text-on-dark-muted (10.44:1)"
    ],
    "validLargeText": [],
    "forbidden": [
      "text-faint (2.4:1)"
    ]
  },
  "bg-surface-alt": {
    "hex": "#262A3A",
    "validText": [
      "text-heading (14.24:1)",
      "text-body (9.31:1)",
      "text-muted (4.76:1)",
      "text-on-dark (14.24:1)",
      "text-on-dark-muted (9.31:1)"
    ],
    "validLargeText": [],
    "forbidden": [
      "text-faint (2.14:1)"
    ]
  },
  "bg-surface-muted": {
    "hex": "#2D3142",
    "validText": [
      "text-heading (12.89:1)",
      "text-body (8.43:1)",
      "text-on-dark (12.89:1)",
      "text-on-dark-muted (8.43:1)"
    ],
    "validLargeText": [
      "text-muted (4.3:1)"
    ],
    "forbidden": [
      "text-faint (1.94:1)"
    ]
  },
  "bg-surface-dark": {
    "hex": "#1E2130",
    "validText": [
      "text-heading (15.96:1)",
      "text-body (10.44:1)",
      "text-muted (5.33:1)",
      "text-on-dark (15.96:1)",
      "text-on-dark-muted (10.44:1)"
    ],
    "validLargeText": [],
    "forbidden": [
      "text-faint (2.4:1)"
    ]
  },
  "bg-surface-dark-alt": {
    "hex": "#3B4055",
    "validText": [
      "text-heading (10.24:1)",
      "text-body (6.7:1)",
      "text-on-dark (10.24:1)",
      "text-on-dark-muted (6.7:1)"
    ],
    "validLargeText": [
      "text-muted (3.42:1)"
    ],
    "forbidden": [
      "text-faint (1.54:1)"
    ]
  }
};
