// AUTO-GENERATED by scripts/generate-pairings.ts
// Re-run: npm run generate:pairings
//
// This file is the agent lookup table for safe color pairings.
// Before applying any dark: text token override, verify the pairing here.
//
// Legend:
//   validText      — contrast >=4.5:1 — safe for all text sizes
//   validLargeText — contrast >=3:1   — large text (>=18px) or UI elements only
//   forbidden      — contrast <3:1    — NEVER use for text or interactive elements

export interface TokenPairing {
  hex: string;
  validText: string[];
  validLargeText: string[];
  forbidden: string[];
}

export const lightMode: Record<string, TokenPairing> = {
  "bg-bg-primary": {
    "hex": "#FFFFFF",
    "validText": [
      "text-text-primary (17.85:1)",
      "text-text-secondary (10.35:1)",
      "text-text-muted (7.58:1)",
      "text-accent-primary (5.93:1)",
      "text-accent-secondary (7.58:1)",
      "text-success (7.68:1)",
      "text-danger (8.31:1)"
    ],
    "validLargeText": [],
    "forbidden": []
  },
  "bg-bg-card": {
    "hex": "#F8FAFC",
    "validText": [
      "text-text-primary (17.06:1)",
      "text-text-secondary (9.9:1)",
      "text-text-muted (7.24:1)",
      "text-accent-primary (5.67:1)",
      "text-accent-secondary (7.25:1)",
      "text-success (7.34:1)",
      "text-danger (7.94:1)"
    ],
    "validLargeText": [],
    "forbidden": []
  },
  "bg-bg-hover": {
    "hex": "#F1F5F9",
    "validText": [
      "text-text-primary (16.3:1)",
      "text-text-secondary (9.45:1)",
      "text-text-muted (6.92:1)",
      "text-accent-primary (5.42:1)",
      "text-accent-secondary (6.92:1)",
      "text-success (7.01:1)",
      "text-danger (7.59:1)"
    ],
    "validLargeText": [],
    "forbidden": []
  }
};

export const darkMode: Record<string, TokenPairing> = {
  "bg-bg-primary": {
    "hex": "#0F172A",
    "validText": [
      "text-text-primary (16.3:1)",
      "text-text-secondary (12.02:1)",
      "text-text-muted (8.54:1)",
      "text-accent-primary (10.71:1)",
      "text-accent-secondary (12.32:1)",
      "text-success (11.71:1)",
      "text-danger (9.41:1)"
    ],
    "validLargeText": [],
    "forbidden": []
  },
  "bg-bg-card": {
    "hex": "#1E293B",
    "validText": [
      "text-text-primary (13.35:1)",
      "text-text-secondary (9.85:1)",
      "text-text-muted (7:1)",
      "text-accent-primary (8.77:1)",
      "text-accent-secondary (10.09:1)",
      "text-success (9.6:1)",
      "text-danger (7.71:1)"
    ],
    "validLargeText": [],
    "forbidden": []
  },
  "bg-bg-hover": {
    "hex": "#334155",
    "validText": [
      "text-text-primary (9.45:1)",
      "text-text-secondary (6.97:1)",
      "text-text-muted (4.95:1)",
      "text-accent-primary (6.21:1)",
      "text-accent-secondary (7.14:1)",
      "text-success (6.79:1)",
      "text-danger (5.46:1)"
    ],
    "validLargeText": [],
    "forbidden": []
  }
};
