apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "njord-postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  POSTGRES_PASSWORD: {{ include "njord-postgres.password" . | quote }}
