name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.job.yaml

  test:
    uses: ./.github/workflows/test.job.yaml

  build:
    uses: ./.github/workflows/build.job.yaml

  smoke-tests:
    needs: [lint, test, build]
    uses: ./.github/workflows/smoke-tests.job.yaml
