name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/**"

permissions: {}

jobs:
  terraform:
    uses: ./.github/workflows/terraform.job.yaml
    with:
      dry_run: false
    secrets:
      CLOUDFLARE_R2_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY }}
      CLOUDFLARE_R2_SECRET_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_KEY }}
      TF_CF_API_KEY: ${{ secrets.TF_CF_API_KEY }}
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
